language: python
python:
- 2.7
- 3.5
script: pytest
env:
- PYTHONPATH=.
deploy:
  provider: pypi
  user: davidcarboni
  password:
    secure: Oy5J9yC0YhR3llD2Djigwkk8tNNaRIMWeZtfTq7SZhOOlxnVaSqJJLdpMWsYJuy+HPQrzevgChO1cOqTp6rUsdiZ78lNzQhbLCe6wLQBAsiJLDyPTCpKuJl6dW4hld9JgJfsgT01i150abmRd3hLa/RDlt4A1sFxoP9doaP5R7CKZQ5WmAp8BnygZGOUAQuSiEqg1DRJfNk213BFJQZ4m5sKvtwKqCe+FgpxgQpEDptcdt9G5I5ZIYVvLHRZqyptEbL7SNxESKHkaaxTHuiBqBMJ8GponVv12rbAiD5AmpgM8CJ3g5CcYxBucTosZEeBMMfEh9UCgW3xPCNudOh9YcD4NCUndbeM4ZM6siEoEO4gNyByG0cqIShTTXrwqhlvUfaN/eVlh2mpTaXfAJ3yoVVrA6RFH9bBgv2ZdTmR0Lbc6c/VzgWcKj6c4hUIE9GLWNKViirjRr3mEkYVMkptgmBtlluwnb+em3DaUvwUegOWJaqUrAwNMMNp6eJhwQNvis+PVInwxM30CFeZ11+CpbFUabiZUVFzDPjBOx7wakL89P2CbOk+5QeNTldEX3Zj3QSFfabtxuEDkBhXTmH2i/setoABL2CavyQPu3lUxp0SOP5edriaBuXnwBLDVh5fSw/b02tN+j6c7FdPHdQdhIvXV2AjiGKF7KYdM3M1i/c=
