language: python
python:
- 2.7
- 3.5
script: pytest
env:
- PYTHONPATH=.
deploy:
  provider: pypi
  user: davidcarboni
  password:
    secure: HZgd9mVm0hqObhCO70JLMijZM+sw4z7dQWsfLUDfGClW/sZxLl8oEtldriel151kTuo+eHZI9QmJRgbaDha69CJRaE+NZqKxB0GyjXsjOBmUyGHVKbl/XbIo5wrv5ZxAISiIjjNl1css3u3I/R5th6UZ/uPDQdgHw1+bgvCv9FPLHsCss50N3IpnzXQtzBWNsSss57MyAmr60C5s6HYHgGzSCl9htqALOWulZF3sdLpWA9xUCMfd9tWl+6ONPss0b+ZAv1PJwIWzdw6vR8kSVG+o0DxGfl9y/I1ezU4kZqFqfWcgwwUAlr1k/fVBWb5ImT3nGd75s1J+DTJUulnh6yWIlTVakL13ClzQ1V/nFmRSQxonXYMujEp8PwjoMl2XQRySIOHqkFPmqSppIQl2jhghCxaNHV0XQ9m2bmYpI2VzO1Tmpl6VNERSRGQcjxRFg+Nvq28WGMCweki5iqFbb/91EY/EqGlKlcxMaSjDJIW0cafeqCb5NsRITl2Oba6glOxjKlJUu9+qVwlEcV2JpPjmTsDCro7GoHhIV8rc4Dsd9ceLOQycxKQB6SejcgtSy2FhKZEe+UMQOFfXnhARHP9+YZ6K1sUm+OyiPSag3fO5kTH+0Iu4nm2Py2c03mxw/Wc8uzI/0/CFZzM8Cz+ZAx5hbmY3BZHH1GujpmmbNlk=
  on:
    tags: true
