language: python
python:
- 2.7
- 3.5
script: pytest
env:
- PYTHONPATH=.
before_deploy: echo Deploying to Pypi..
after_deploy: echo Deployed to Pypi.
deploy:
  provider: pypi
  user: davidcarboni
  on:
    tags: true
    branch: master
  password:
    secure: K1GWa9j8eBxVF5Z4az3IojKf3u6z3WsDy6oEvgivgUJOAcDOMYD/UtNK6vD9BaKKKIhVC+TP+fPWZ9tn5inWP7K//MJi9EUB/bNsuLY2FNMqMIqLjBhOT9hzreOLnJvaQw3YZ9SzVnJavS+2ZSMNxioQGxRpr5QPh+s46gqoSvhqcveLwC0BDPMC+l2eWsTgp9H7GS8d7Qy1KR51n9kJR6CW1uvoas0TfV0BupHOwBex+RUfbYgWythTiU7Rf2VcBAAXIRNqw4VyMJPt2Xy4UKblvxuMVJJbY5fQTJfD7s4gi9ZvBYJzqXtzczdFAgyXFFd7IHqrEpUzOvlxk5ADC7cp/6tXMKfYwMPzws7384CbehbRo4tJgKX9ZZYH8tJuh+IRO9xtb+yNf8NoQQ2KLwK8bjSRMI5OuxVu8jTnMArhPern4oXfzfkkKyFt3A8SEK/PJKY9HLDVxsZHzmGtglCn/tl0fHzTPLdwo/ZRrDyRaSlo24epaC7Rrp1pWDgDv2dZiQenDEw8fR4MX+8PfnwnPy9RU34qWYInB4wZHZbueK8WANjCErRa9/oOTNY6tIR8867R9TsEhWV//vflFD2JpmHTuWDunrkPjNUOg07vICVOKE3sDOwnS2lvy89Psi33FSr4jAAi8KzHLtuF9nUxqFfplL3G+TjClqEzQAw=
